query GetGlobalReports($limit: Int!, $offset: Int!) {
  globalReports(limit: $limit, offset: $offset) {
    limit
    offset
    total
    items {
      ...ReportDetail
    }
  }
}
fragment ReportDetail on RSReport {
  id
  name

  reportType {
    ...ReportTypeDetail
  }
  description
  createdAt
  updatedAt

  createdBy {
    ...DEProfileSummary
  }

  status
  progress

  parameters
  errorMessage
  centroid
  extent
}