fragment ReportDetail on RSReport {
  id
  name

  reportType {
    ...ReportTypeDetail
  }
  description
  createdAt
  updatedAt

  createdBy {
    ...DEProfileSummary
  }

  status
  progress

  parameters
  errorMessage
  centroid
  extent
}